### ISSUE TITLE
Loading file .desktop issue

### ISSUE THREAD

**Issue by stefonarch** [elviosak/plugin-wingmenu#14]
When trying to load a file .desktop in "Leave actions" none are displayed:

![schermata-18 lug 22:56](https://user-images.githubusercontent.com/10681413/179616212-6a8f219d-5df5-456b-8a27-f8d3df374e57.png)

**Comment by elviosak** [comment]
Allowed all files, looks like this is the only way because the dialog only displays the "Name" field from desktop files and not their filenames. Looks like a bug in Qt or whatever provides the file dialog.

**Comment by elviosak** [comment]
Found this: https://github.com/lxqt/libfm-qt/issues/193
