### ISSUE TITLE
Doubling bookmarks items 

### ISSUE THREAD

**Issue by stefonarch** [elviosak/plugin-wingmenu#20]
I saw it happen several times on both machines (debian testing/arch) in the last days: the favorite list starts again after the last item.

* I still am not able to trigger it precisely unfortunately
* I suspect it happens with local favorites from `~/.local/share/applications` when editing them, or adding new ones.

Now I eliminated all local favorites, waiting. Sorry for not being more precise.

**Comment by stefonarch** [comment]
For 2 days nothing, editing and readding a modified local desktop file it happened again,  but I still cannot reproduce it. 

![schermata-23 lug 16:28-01](https://user-images.githubusercontent.com/10681413/180612328-f1adba71-0bb3-44e3-945c-dcce7c978607.png)

**Comment by elviosak** [comment]
Should be fixed now.
