### ISSUE TITLE
Issue Compiling Wingmenu on Debain 11

### ISSUE THREAD

**Issue by subhaniminhas** [elviosak/plugin-wingmenu#29]
While trying to compile WingMenu on Debian 11, i encountered following errors:
bash install.sh
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:37 (find_package):
  Could not find a configuration file for package "Qt5Widgets" that is
  compatible with requested version "5.15.3".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.15.2
    /lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.15.2

-- Configuring incomplete, errors occurred!
See also "/home/pakuser/plugin-wingmenu/build/CMakeFiles/CMakeOutput.log".

**Comment by stefonarch** [comment]
> Could not find a configuration file for package "Qt5Widgets" that is
compatible with requested version "5.15.3".

Debian 11 has a to old Qt version (and also for compiling LXQt)

**Comment by subhaniminhas** [comment]
Can anything be done at your end? Or at my end? I wanted to make it part of latest build of PakOS. It would be ideal if Debian 11 compatible Debs could be provided. Thx.

**Comment by stefonarch** [comment]
Atm it can't be distributed afaik, see https://github.com/elviosak/plugin-wingmenu/issues/10
