### ISSUE TITLE
Last selection is not cleared at reopening

### ISSUE THREAD

**Issue by stefonarch** [elviosak/plugin-wingmenu#7]
It's some kind of random, but usually something is selected already  when opening the menu, depending where the selection was.

Steps to reproduce:
1) select one favorite, launch it or exit the menu moving the cursor out of it
2) reopen it and hit enter, the previous selection is still there and will be launched.

With item of the categories it's different, another item is selected at reopening, didn't track down the mechanism.

**Comment by elviosak** [comment]
This [commit](https://github.com/slidinghotdog/plugin-wingmenu/commit/1883a7385ea7341725cededabd3a39a9cef06890) makes it remove selections when hiding panel.
